//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace MaaFramework.Binding.Interop.Native;

public static partial class MaaAgentClient
{
    [LibraryImport("MaaAgentClient", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaAgentClientHandle MaaAgentClientCreateV2(MaaStringBufferHandle identifier);

    [LibraryImport("MaaAgentClient", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaAgentClientDestroy(MaaAgentClientHandle client);

    [LibraryImport("MaaAgentClient", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaAgentClientIdentifier(MaaAgentClientHandle client, MaaStringBufferHandle identifier);

    [LibraryImport("MaaAgentClient", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaAgentClientBindResource(MaaAgentClientHandle client, MaaResourceHandle res);

    [LibraryImport("MaaAgentClient", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaAgentClientRegisterSink(MaaAgentClientHandle client, MaaTaskerHandle tasker, MaaResourceHandle res, MaaControllerHandle ctrl);

    [LibraryImport("MaaAgentClient", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaAgentClientConnect(MaaAgentClientHandle client);

    [LibraryImport("MaaAgentClient", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaAgentClientDisconnect(MaaAgentClientHandle client);

    [LibraryImport("MaaAgentClient", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaAgentClientConnected(MaaAgentClientHandle client);

    [LibraryImport("MaaAgentClient", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaAgentClientAlive(MaaAgentClientHandle client);

    [LibraryImport("MaaAgentClient", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaAgentClientSetTimeout(MaaAgentClientHandle client, long milliseconds);

    [Obsolete]
    [LibraryImport("MaaAgentClient", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaAgentClientHandle MaaAgentClientCreate();

    [Obsolete]
    [LibraryImport("MaaAgentClient", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaAgentClientCreateSocket(MaaAgentClientHandle client, MaaStringBufferHandle identifier);
}
