//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

namespace MaaFramework.Binding;

/// <remarks>
///     <para>Use bitwise OR to set the method you need, MaaFramework will select the available ones according to priority. The priority is: EmulatorExtras > Maatouch > MinitouchAndAdbKey > AdbShell</para>
/// </remarks>
[Flags]
public enum AdbInputMethods : System.UInt64
{
    AdbShell = 1,
    MinitouchAndAdbKey = (1 << 1),
    Maatouch = (1 << 2),
    EmulatorExtras = (1 << 3),
    None = 0,
    All = (~None),
    Default = (All & (~EmulatorExtras)),
}

