//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

namespace MaaFramework.Binding;

/// <summary>
///     Adb input method flags
/// <para>Use bitwise OR to set the methods you need.</para>
/// <para>MaaFramework will select the first available method according to priority.</para>
/// <para>Priority (high to low): EmulatorExtras > Maatouch > MinitouchAndAdbKey > AdbShell</para>
/// <para>Default: All methods except EmulatorExtras</para>
/// <code>| Method               | Speed | Compatibility | Notes                                 |</code>
/// <code>|----------------------|-------|---------------|---------------------------------------|</code>
/// <code>| AdbShell             | Slow  | High          |                                       |</code>
/// <code>| MinitouchAndAdbKey   | Fast  | Medium        | Key press still uses AdbShell         |</code>
/// <code>| Maatouch             | Fast  | Medium        |                                       |</code>
/// <code>| EmulatorExtras       | Fast  | Low           | Emulators only: MuMu 12               |</code>
/// </summary>
[Flags]
public enum AdbInputMethods : System.UInt64
{
    AdbShell = 1,
    MinitouchAndAdbKey = (1 << 1),
    Maatouch = (1 << 2),
    EmulatorExtras = (1 << 3),
    None = 0,
    All = (~None),
    Default = (All & (~EmulatorExtras)),
}

