//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

namespace MaaFramework.Binding;

/// <summary>
///     Adb screencap method flags.
/// <para>Use bitwise OR to set the methods you need.</para>
/// <para>MaaFramework will test all provided methods and use the fastest available one.</para>
/// <para>Default: All methods except RawByNetcat, MinicapDirect, MinicapStream</para>
/// <para>Note: MinicapDirect and MinicapStream use lossy JPEG encoding, which may</para>
/// <para>significantly reduce template matching accuracy. Not recommended.</para>
/// <code>| Method                | Speed      | Compatibility | Encoding | Notes                               |</code>
/// <code>|-----------------------|------------|---------------|----------|-------------------------------------|</code>
/// <code>| EncodeToFileAndPull   | Slow       | High          | Lossless |                                     |</code>
/// <code>| Encode                | Slow       | High          | Lossless |                                     |</code>
/// <code>| RawWithGzip           | Medium     | High          | Lossless |                                     |</code>
/// <code>| RawByNetcat           | Fast       | Low           | Lossless |                                     |</code>
/// <code>| MinicapDirect         | Fast       | Low           | Lossy    |                                     |</code>
/// <code>| MinicapStream         | Very Fast  | Low           | Lossy    |                                     |</code>
/// <code>| EmulatorExtras        | Very Fast  | Low           | Lossless | Emulators only: MuMu 12, LDPlayer 9 |</code>
/// </summary>
[Flags]
public enum AdbScreencapMethods : System.UInt64
{
    EncodeToFileAndPull = 1,
    Encode = (1 << 1),
    RawWithGzip = (1 << 2),
    RawByNetcat = (1 << 3),
    MinicapDirect = (1 << 4),
    MinicapStream = (1 << 5),
    EmulatorExtras = (1 << 6),
    None = 0,
    All = (~None),
    Default = (All & (~RawByNetcat) & (~MinicapDirect) & (~MinicapStream)),
}

