//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

namespace MaaFramework.Binding;

/// <summary>
///     Virtual gamepad type.
///     <para>Select ONE type only.</para>
///     <code>| Type          | Description                                    |</code>
///     <code>|---------------|------------------------------------------------|</code>
///     <code>| Xbox360       | Microsoft Xbox 360 Controller (wired)          |</code>
///     <code>| DualShock4    | Sony DualShock 4 Controller (wired)            |</code>
/// </summary>
public enum GamepadType : System.UInt64
{
    Xbox360 = 0UL,
    DualShock4 = 1UL,
}
