//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

namespace MaaFramework.Binding;

/// <summary>
///     Virtual gamepad button codes for <see cref="IMaaController.ClickKey(int)"/> / <see cref="IMaaController.KeyDown(int)"/> / <see cref="IMaaController.KeyUp(int)"/>
///     
/// <para>Use these values with MaaControllerPostClickKey, MaaControllerPostKeyDown, MaaControllerPostKeyUp.
/// <br/>Values are based on XUSB (Xbox 360) button flags. DS4 face buttons are mapped to Xbox equivalents.</para>
/// 
/// <para>Xbox 360 buttons:</para>
/// 
/// <code>| Value   | Button              | Description            |
/// <br/>|---------|---------------------|------------------------|
/// <br/>| 0x1000  | A                   | A button               |
/// <br/>| 0x2000  | B                   | B button               |
/// <br/>| 0x4000  | X                   | X button               |
/// <br/>| 0x8000  | Y                   | Y button               |
/// <br/>| 0x0100  | LB (Left Shoulder)  | Left bumper            |
/// <br/>| 0x0200  | RB (Right Shoulder) | Right bumper           |
/// <br/>| 0x0040  | L_THUMB             | Left stick click       |
/// <br/>| 0x0080  | R_THUMB             | Right stick click      |
/// <br/>| 0x0010  | START               | Start button           |
/// <br/>| 0x0020  | BACK                | Back button            |
/// <br/>| 0x0400  | GUIDE               | Guide/Home button      |
/// <br/>| 0x0001  | DPAD_UP             | D-pad up               |
/// <br/>| 0x0002  | DPAD_DOWN           | D-pad down             |
/// <br/>| 0x0004  | DPAD_LEFT           | D-pad left             |
/// <br/>| 0x0008  | DPAD_RIGHT          | D-pad right            |
/// </code>
/// 
/// <para>DualShock 4 buttons (aliases to Xbox buttons):</para>
/// 
/// <code>| Value   | Button    | Xbox Equivalent | Description               |
/// <br/>|---------|-----------|-----------------|---------------------------|
/// <br/>| 0x1000  | CROSS     | A               | Cross (X) button          |
/// <br/>| 0x2000  | CIRCLE    | B               | Circle button             |
/// <br/>| 0x4000  | SQUARE    | X               | Square button             |
/// <br/>| 0x8000  | TRIANGLE  | Y               | Triangle button           |
/// <br/>| 0x0100  | L1        | LB              | L1 button                 |
/// <br/>| 0x0200  | R1        | RB              | R1 button                 |
/// <br/>| 0x0040  | L3        | L_THUMB         | Left stick click          |
/// <br/>| 0x0080  | R3        | R_THUMB         | Right stick click         |
/// <br/>| 0x0010  | OPTIONS   | START           | Options button            |
/// <br/>| 0x0020  | SHARE     | BACK            | Share button              |
/// <br/>| 0x10000 | PS        | -               | PS button (DS4 special)   |
/// <br/>| 0x20000 | TOUCHPAD  | -               | Touchpad click (DS4 only) |
/// </code>
/// 
/// </summary>
[Flags]
public enum GamepadButton : System.UInt64
{
    // Xbox 360 buttons (XUSB protocol values)
    A = 0x1000,
    B = 0x2000,
    X = 0x4000,
    Y = 0x8000,
    LB = 0x0100,
    RB = 0x0200,
    LEFT_THUMB = 0x0040,
    RIGHT_THUMB = 0x0080,
    START = 0x0010,
    BACK = 0x0020,
    GUIDE = 0x0400,
    DPAD_UP = 0x0001,
    DPAD_DOWN = 0x0002,
    DPAD_LEFT = 0x0004,
    DPAD_RIGHT = 0x0008,

    // DualShock 4 face buttons (aliases to Xbox face buttons)
    CROSS = A,
    CIRCLE = B,
    SQUARE = X,
    TRIANGLE = Y,
    L1 = LB,
    R1 = RB,
    L3 = LEFT_THUMB,
    R3 = RIGHT_THUMB,
    OPTIONS = START,
    SHARE = BACK,

    // DualShock 4 special buttons (unique values, no Xbox equivalent)
    PS = 0x10000,
    TOUCHPAD = 0x20000,
}
