//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

namespace MaaFramework.Binding;

/// <summary>
///     Virtual gamepad touch contact definitions for touch_down/touch_move/touch_up.
/// </summary>
/// <remarks>
///     <para>For gamepad controller, the touch functions are repurposed for analog inputs:</para>
///     <para>- x, y: Analog stick position</para>
///     <para>- pressure: Trigger value (0~255)</para>
///     <code>| Contact       | Input           | x range       | y range       | pressure   | Description                      |</code>
///     <code>|---------------|-----------------|---------------|---------------|------------|----------------------------------|</code>
///     <code>| LeftStick     | Left Stick      | -32768~32767  | -32768~32767  | ignored    | Left analog stick X/Y position   |</code>
///     <code>| RightStick    | Right Stick     | -32768~32767  | -32768~32767  | ignored    | Right analog stick X/Y position  |</code>
///     <code>| LeftTrigger   | Left Trigger    | ignored       | ignored       | 0~255      | Left trigger (LT/L2) value       |</code>
///     <code>| RightTrigger  | Right Trigger   | ignored       | ignored       | 0~255      | Right trigger (RT/R2) value      |</code>
/// </remarks>
public enum GamepadTouch : System.UInt64
{
    LeftStick = 0,
    RightStick = 1,
    LeftTrigger = 2,
    RightTrigger = 3,
}
