//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

namespace MaaFramework.Binding;

/// <summary>
///     Virtual gamepad button codes for click_key/key_down/key_up.
/// </summary>
/// <remarks>
///     <para>Use these values with ClickKey, KeyDown, KeyUp.</para>
///     <para>Values are based on XUSB (Xbox 360) button flags. DS4 face buttons are mapped to Xbox equivalents.</para>
/// </remarks>
[Flags]
public enum GamepadButton : System.UInt64
{
    // Xbox 360 buttons (XUSB protocol values)
    A = 0x1000,
    B = 0x2000,
    X = 0x4000,
    Y = 0x8000,
    LB = 0x0100,
    RB = 0x0200,
    LeftThumb = 0x0040,
    RightThumb = 0x0080,
    Start = 0x0010,
    Back = 0x0020,
    Guide = 0x0400,
    DPadUp = 0x0001,
    DPadDown = 0x0002,
    DPadLeft = 0x0004,
    DPadRight = 0x0008,

    // DualShock 4 face buttons (aliases to Xbox face buttons)
    Cross = A,
    Circle = B,
    Square = X,
    Triangle = Y,
    L1 = LB,
    R1 = RB,
    L3 = LeftThumb,
    R3 = RightThumb,
    Options = Start,
    Share = Back,

    // DualShock 4 special buttons (unique values, no Xbox equivalent)
    PS = 0x10000,
    Touchpad = 0x20000,
}
