//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

namespace MaaFramework.Binding;

/// <summary>
///     Virtual gamepad touch contact definitions for <see cref="IMaaController.TouchDown(int, int, int, int)"/> / <see cref="IMaaController.TouchMove(int, int, int, int)"/> / <see cref="IMaaController.TouchUp(int)"/>
///     
/// <para>For gamepad controller, the touch functions are repurposed for analog inputs:
/// <br/>- x, y: Analog stick position
/// <br/>- pressure: Trigger value (0~255)</para>
/// 
/// <para>Contact mapping:</para>
/// 
/// <code>| Contact       | Input           | x range       | y range       | pressure   | Description                      |
/// <br/>|---------------|-----------------|---------------|---------------|------------|----------------------------------|
/// <br/>| LeftStick     | Left Stick      | -32768~32767  | -32768~32767  | ignored    | Left analog stick X/Y position   |
/// <br/>| RightStick    | Right Stick     | -32768~32767  | -32768~32767  | ignored    | Right analog stick X/Y position  |
/// <br/>| LeftTrigger   | Left Trigger    | ignored       | ignored       | 0~255      | Left trigger (LT/L2) value       |
/// <br/>| RightTrigger  | Right Trigger   | ignored       | ignored       | 0~255      | Right trigger (RT/R2) value      |
/// </code>
/// 
/// <para>Usage:
/// <br/>- touch_down(contact, x, y, pressure): Start analog input
/// <br/>- touch_move(contact, x, y, pressure): Update analog input position/value
/// <br/>- touch_up(contact): Release/reset analog input to center/zero</para>
/// 
/// </summary>
public enum GamepadTouch : System.UInt64
{
    LeftStick = 0,
    RightStick = 1,
    LeftTrigger = 2,
    RightTrigger = 3,
}
