//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

namespace MaaFramework.Binding;

/// <summary>
///     MacOS input method.
///
/// <para>Select ONE method only.</para>
/// 
/// <code>| Method          | Description                                                                                                        |
/// <br/>|-----------------|--------------------------------------------------------------------------------------------------------------------|
/// <br/>| GlobalEvent     | Injects into the global HID event stream via CGEventPost(kCGHIDEventTap), dispatched by the OS to the front window |
/// <br/>| PostToPid       | Directly send to target process using CGEventPostToPid                                                             |
/// </code>
/// 
/// </summary>
public enum MacOSInputMethod : System.UInt64
{
    None = 0,
    GlobalEvent = 1,
    PostToPid = (1 << 1),
}
