//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

namespace MaaFramework.Binding;

/// <remarks>
///     <para>No bitwise OR, just set it</para>
/// </remarks>
public enum Win32ScreencapMethod : System.UInt64
{
    None = 0,
    GDI = 1,
    FramePool = (1 << 1),
    DXGI_DesktopDup = (1 << 2),
    DXGI_DesktopDup_Window = (1 << 3),
    PrintWindow = (1 << 4),
    ScreenDC = (1 << 5),
}

