//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

namespace MaaFramework.Binding;

/// <summary>
///     Win32 input method
/// 
/// <para>No bitwise OR, select ONE method only.</para>
/// 
/// <para>No default value. Client should choose one as default.</para>
/// 
/// <para>Different applications process input differently, there is no universal solution.</para>
/// 
/// <code>| Method                   | Compatibility | Require Admin | Seize Mouse  | Background Support | Notes                                    |
/// <br/>|--------------------------|---------------|---------------|--------------|--------------------|------------------------------------------|
/// <br/>| Seize                    | High          | No            | Yes          | No  |                                                         |
/// <br/>| SendMessage              | Medium        | Maybe         | No           | Yes |                                                         |
/// <br/>| PostMessage              | Medium        | Maybe         | No           | Yes |                                                         |
/// <br/>| LegacyEvent              | Low           | No            | Yes          | No  |                                                         |
/// <br/>| PostThreadMessage        | Low           | Maybe         | No           | Yes |                                                         |
/// <br/>| SendMessageWithCursorPos | Medium        | Maybe         | Briefly      | Yes | Moves cursor to target position, then restores          |
/// <br/>| PostMessageWithCursorPos | Medium        | Maybe         | Briefly      | Yes | Moves cursor to target position, then restores          |
/// <br/>| SendMessageWithWindowPos | Medium        | Maybe         | No           | Yes | Moves window to align target with cursor, then restores |
/// <br/>| PostMessageWithWindowPos | Medium        | Maybe         | No           | Yes | Moves window to align target with cursor, then restores |
/// </code>
/// 
/// <para>Note:
/// <br/>- Admin rights mainly depend on the target application's privilege level.
/// <br/>  If the target runs as admin, MaaFramework should also run as admin for compatibility.
/// <br/>- "WithCursorPos" methods briefly move the cursor to target position, send message,
/// <br/>  then restore cursor position. This "briefly" seizes the mouse but won't block user operations.
/// <br/>- "WithWindowPos" methods briefly move the window so the target aligns with the current cursor
/// <br/>  position, send message, then restore the window position. The cursor is not moved.</para>
/// 
/// </summary>
public enum Win32InputMethod : System.UInt64
{
    None = 0,
    Seize = 1,
    SendMessage = (1 << 1),
    PostMessage = (1 << 2),
    LegacyEvent = (1 << 3),
    [Obsolete("Deprecated from MaaFramework v5.9.0.")]
    PostThreadMessage = (1 << 4),
    SendMessageWithCursorPos = (1 << 5),
    PostMessageWithCursorPos = (1 << 6),
    SendMessageWithWindowPos = (1 << 7),
    PostMessageWithWindowPos = (1 << 8),
}

