//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

namespace MaaFramework.Binding;

/// <summary>
///     Win32 screencap method
/// <para>No bitwise OR, select ONE method only.</para>
/// <para>No default value. Client should choose one as default.</para>
/// <para>Different applications use different rendering methods, there is no universal solution.</para>
/// <code>| Method                  | Speed     | Compatibility | Require Admin | Background Support | Notes                            |</code>
/// <code>|-------------------------|-----------|---------------|---------------|--------------------|----------------------------------|</code>
/// <code>| GDI                     | Fast      | Medium        | No            | No                 |                                  |</code>
/// <code>| FramePool               | Very Fast | Medium        | No            | Yes                | Requires Windows 10 1903+        |</code>
/// <code>| DXGI_DesktopDup         | Very Fast | Low           | No            | No                 | Desktop duplication (full screen)|</code>
/// <code>| DXGI_DesktopDup_Window  | Very Fast | Low           | No            | No                 | Desktop duplication then crop    |</code>
/// <code>| PrintWindow             | Medium    | Medium        | No            | Yes                |                                  |</code>
/// <code>| ScreenDC                | Fast      | High          | No            | No                 |                                  |</code>
/// <para>Note: FramePool and PrintWindow support pseudo-minimize — when the target window
/// is minimized, they make it transparent and click-through, then restore it without
/// activation, allowing screencap to continue without disturbing the user.</para>
/// <para>Other screencap methods will fail when the target window is minimized.</para>
/// </summary>
public enum Win32ScreencapMethod : System.UInt64
{
    None = 0,
    GDI = 1,
    FramePool = (1 << 1),
    DXGI_DesktopDup = (1 << 2),
    DXGI_DesktopDup_Window = (1 << 3),
    PrintWindow = (1 << 4),
    ScreenDC = (1 << 5),
}

