//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

namespace MaaFramework.Binding;

/// <summary>
///     Win32 screencap method flags
/// 
/// <para>Use bitwise OR to set the methods you need.
/// <br/>MaaFramework will test all provided methods and use the fastest available one.</para>
/// 
/// <para>No default value. Client should choose one as default.</para>
/// 
/// <para>Predefined combinations:
/// <br/>- Foreground: DXGI_DesktopDup_Window | ScreenDC
/// <br/>- Background: FramePool | PrintWindow</para>
/// 
/// <para>Different applications use different rendering methods, there is no universal solution.</para>
/// 
/// <code>| Method                  | Speed     | Compatibility | Require Admin | Background Support | Notes                            |
/// <br/>|-------------------------|-----------|---------------|---------------|--------------------|----------------------------------|
/// <br/>| GDI                     | Fast      | Medium        | No            | No                 |                                  |
/// <br/>| FramePool               | Very Fast | Medium        | No            | Yes                | Requires Windows 10 1903+        |
/// <br/>| DXGI_DesktopDup         | Very Fast | Low           | No            | No                 | Desktop duplication (full screen)|
/// <br/>| DXGI_DesktopDup_Window  | Very Fast | Low           | No            | No                 | Desktop duplication then crop    |
/// <br/>| PrintWindow             | Medium    | Medium        | No            | Yes                |                                  |
/// <br/>| ScreenDC                | Fast      | High          | No            | No                 |                                  |
/// </code>
/// 
/// <para>Note: FramePool and PrintWindow support pseudo-minimize — when the target window
///     <br/>is minimized, they make it transparent and click-through, then restore it without
///     <br/>activation, allowing screencap to continue without disturbing the user.
///     <br/>Other screencap methods will fail when the target window is minimized.</para>
/// 
/// </summary>
[Flags]
public enum Win32ScreencapMethods : System.UInt64
{
    None = 0,
    GDI = 1,
    FramePool = (1 << 1),
    DXGI_DesktopDup = (1 << 2),
    DXGI_DesktopDup_Window = (1 << 3),
    PrintWindow = (1 << 4),
    ScreenDC = (1 << 5),

    All = ~None,
    Foreground = DXGI_DesktopDup_Window | ScreenDC,
    Background = FramePool | PrintWindow,
}

