//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

namespace MaaFramework.Binding;

/// <summary>
///     Win32 input method
/// <para>No bitwise OR, select ONE method only.</para>
/// <para>No default value. Client should choose one as default.</para>
/// <para>Different applications process input differently, there is no universal solution.</para>
/// <code>| Method                   | Compatibility | Require Admin | Seize Mouse  | Background Support | Notes                              |</code>
/// <code>|--------------------------|---------------|---------------|--------------|--------------------|------------------------------------|</code>
/// <code>| Seize                    | High          | No            | Yes          | No  |                                                   |</code>
/// <code>| SendMessage              | Medium        | Maybe         | No           | Yes |                                                   |</code>
/// <code>| PostMessage              | Medium        | Maybe         | No           | Yes |                                                   |</code>
/// <code>| LegacyEvent              | Low           | No            | Yes          | No  |                                                   |</code>
/// <code>| PostThreadMessage        | Low           | Maybe         | No           | Yes |                                                   |</code>
/// <code>| SendMessageWithCursorPos | Medium        | Maybe         | Briefly      | Yes | Designed for apps that check real cursor position |</code>
/// <code>| PostMessageWithCursorPos | Medium        | Maybe         | Briefly      | Yes | Designed for apps that check real cursor position |</code>
/// <para>Note:</para>
/// <para>- Admin rights mainly depend on the target application's privilege level.</para>
/// <para>If the target runs as admin, MaaFramework should also run as admin for compatibility.</para>
/// <para>- "WithCursorPos" methods briefly move the cursor to target position, send message,</para>
/// <para>then restore cursor position. This "briefly" seizes the mouse but won't block user operations.</para>
/// </summary>
public enum Win32InputMethod : System.UInt64
{
    None = 0,
    Seize = 1,
    SendMessage = (1 << 1),
    PostMessage = (1 << 2),
    LegacyEvent = (1 << 3),
    PostThreadMessage = (1 << 4),
    SendMessageWithCursorPos = (1 << 5),
    PostMessageWithCursorPos = (1 << 6),
}

