//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

using System.Runtime.InteropServices;

namespace MaaFramework.Binding.Interop.Native;

public static partial class MaaToolkit
{
    [LibraryImport("MaaToolkit", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaToolkitAdbDeviceListHandle MaaToolkitAdbDeviceListCreate();

    [LibraryImport("MaaToolkit", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaToolkitAdbDeviceListDestroy(MaaToolkitAdbDeviceListHandle handle);

    [LibraryImport("MaaToolkit", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaToolkitAdbDeviceFind(MaaToolkitAdbDeviceListHandle buffer);

    [LibraryImport("MaaToolkit", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaToolkitAdbDeviceFindSpecified(string adbPath, MaaToolkitAdbDeviceListHandle buffer);

    [LibraryImport("MaaToolkit", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaSize MaaToolkitAdbDeviceListSize(MaaToolkitAdbDeviceListHandle list);

    [LibraryImport("MaaToolkit", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaToolkitAdbDeviceHandle MaaToolkitAdbDeviceListAt(MaaToolkitAdbDeviceListHandle list, MaaSize index);

    [LibraryImport("MaaToolkit", StringMarshalling = StringMarshalling.Utf8)]
    public static partial nint MaaToolkitAdbDeviceGetName(MaaToolkitAdbDeviceHandle device);

    [LibraryImport("MaaToolkit", StringMarshalling = StringMarshalling.Utf8)]
    public static partial nint MaaToolkitAdbDeviceGetAdbPath(MaaToolkitAdbDeviceHandle device);

    [LibraryImport("MaaToolkit", StringMarshalling = StringMarshalling.Utf8)]
    public static partial nint MaaToolkitAdbDeviceGetAddress(MaaToolkitAdbDeviceHandle device);

    [LibraryImport("MaaToolkit", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaAdbScreencapMethod MaaToolkitAdbDeviceGetScreencapMethods(MaaToolkitAdbDeviceHandle device);

    [LibraryImport("MaaToolkit", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaAdbInputMethod MaaToolkitAdbDeviceGetInputMethods(MaaToolkitAdbDeviceHandle device);

    [LibraryImport("MaaToolkit", StringMarshalling = StringMarshalling.Utf8)]
    public static partial nint MaaToolkitAdbDeviceGetConfig(MaaToolkitAdbDeviceHandle device);
}
