//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

global using MaaStringBufferHandle = nint;
global using MaaImageBufferHandle = nint;
global using MaaStringListBufferHandle = nint;
global using MaaImageListBufferHandle = nint;
global using MaaResourceHandle = nint;
global using MaaControllerHandle = nint;
global using MaaInstanceHandle = nint;
global using MaaBool = System.Byte;
global using MaaSize = System.UInt64;
global using MaaStringView = nint;
global using MaaStatus = System.Int32;
global using MaaLoggingLevel = System.Int32;
global using MaaId = System.Int64;
global using MaaCtrlId = System.Int64;
global using MaaResId = System.Int64;
global using MaaTaskId = System.Int64;
global using MaaRecoId = System.Int64;
global using MaaNodeId = System.Int64;
global using MaaOption = System.Int32;
global using MaaOptionValue = nint;
global using MaaOptionValueSize = System.UInt64;
global using MaaGlobalOption = System.Int32;
global using MaaResOption = System.Int32;
global using MaaCtrlOption = System.Int32;
global using MaaInstOption = System.Int32;
global using MaaAdbControllerType = System.Int32;
global using MaaDbgControllerType = System.Int32;
global using MaaThriftControllerType = System.Int32;
global using MaaWin32ControllerType = System.Int32;
global using MaaWin32Hwnd = nint;
global using MaaTransparentArg = nint;
global using MaaCallbackTransparentArg = nint;
global using MaaResourceCallback = MaaFramework.Binding.Interop.Native.MaaApiCallback;
global using MaaControllerCallback = MaaFramework.Binding.Interop.Native.MaaApiCallback;
global using MaaInstanceCallback = MaaFramework.Binding.Interop.Native.MaaApiCallback;
global using MaaCustomControllerHandle = nint;
global using MaaCustomRecognizerHandle = nint;
global using MaaCustomActionHandle = nint;
global using MaaSyncContextHandle = nint;
global using MaaRectHandle = nint;

using System.Runtime.InteropServices;

namespace MaaFramework.Binding.Interop.Native;

/// <summary>
///     The callback function type.
/// </summary>
/// <param name="msg">The message. See MaaMsg.h</param>
/// <param name="detailsJson">The details in JSON format. See doc in MaaMsg.h</param>
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
public delegate void MaaApiCallback([MarshalAs(UnmanagedType.LPUTF8Str)] string msg, [MarshalAs(UnmanagedType.LPUTF8Str)] string detailsJson, MaaTransparentArg callbackArg);

public static partial class MaaDef
{
    internal const MaaSize MaaNullSize = MaaSize.MaxValue;
    internal const MaaId MaaInvalidId = 0;
    internal const string MaaTaskParamEmpty = "{}";
}
