//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

global using MaaImageRawData = nint;
global using MaaImageEncodedData = nint;

using System.Runtime.InteropServices;

namespace MaaFramework.Binding.Interop.Native;

public static partial class MaaBuffer
{
    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaStringBufferHandle MaaCreateStringBuffer();

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaDestroyStringBuffer(MaaStringBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaIsStringEmpty(MaaStringBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaClearString(MaaStringBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaStringView MaaGetString(MaaStringBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaSize MaaGetStringSize(MaaStringBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSetString(MaaStringBufferHandle handle, string str);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSetStringEx(MaaStringBufferHandle handle, byte[] str, MaaSize size);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaStringListBufferHandle MaaCreateStringListBuffer();

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaDestroyStringListBuffer(MaaStringListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaIsStringListEmpty(MaaStringListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaClearStringList(MaaStringListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaSize MaaGetStringListSize(MaaStringListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaStringBufferHandle MaaGetStringListAt(MaaStringListBufferHandle handle, MaaSize index);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaStringListAppend(MaaStringListBufferHandle handle, MaaStringBufferHandle value);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaStringListRemove(MaaStringListBufferHandle handle, MaaSize index);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaImageBufferHandle MaaCreateImageBuffer();

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaDestroyImageBuffer(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaIsImageEmpty(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaClearImage(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaImageRawData MaaGetImageRawData(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaGetImageWidth(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaGetImageHeight(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaGetImageType(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSetImageRawData(MaaImageBufferHandle handle, MaaImageRawData data, int width, int height, int type);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaImageEncodedData MaaGetImageEncoded(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaSize MaaGetImageEncodedSize(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSetImageEncoded(MaaImageBufferHandle handle, MaaImageEncodedData data, MaaSize size);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaImageListBufferHandle MaaCreateImageListBuffer();

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaDestroyImageListBuffer(MaaImageListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaIsImageListEmpty(MaaImageListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaClearImageList(MaaImageListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaSize MaaGetImageListSize(MaaImageListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaImageBufferHandle MaaGetImageListAt(MaaImageListBufferHandle handle, MaaSize index);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaImageListAppend(MaaImageListBufferHandle handle, MaaImageBufferHandle value);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaImageListRemove(MaaImageListBufferHandle handle, MaaSize index);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaRectHandle MaaCreateRectBuffer();

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaDestroyRectBuffer(MaaRectHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaGetRectX(MaaRectHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaGetRectY(MaaRectHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaGetRectW(MaaRectHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaGetRectH(MaaRectHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSetRect(MaaRectHandle handle, int x, int y, int w, int h);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSetRectX(MaaRectHandle handle, int value);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSetRectY(MaaRectHandle handle, int value);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSetRectW(MaaRectHandle handle, int value);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSetRectH(MaaRectHandle handle, int value);
}
