//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

global using MaaImageRawData = nint;
global using MaaImageEncodedData = nint;

using System.Runtime.InteropServices;

namespace MaaFramework.Binding.Interop.Native;

public static partial class MaaBuffer
{
    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaStringBufferHandle MaaStringBufferCreate();

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaStringBufferDestroy(MaaStringBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaStringBufferIsEmpty(MaaStringBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaStringBufferClear(MaaStringBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial nint MaaStringBufferGet(MaaStringBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaSize MaaStringBufferSize(MaaStringBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaStringBufferSet(MaaStringBufferHandle handle, string str);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaStringBufferSetEx(MaaStringBufferHandle handle, byte[] str, MaaSize size);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaStringListBufferHandle MaaStringListBufferCreate();

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaStringListBufferDestroy(MaaStringListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaStringListBufferIsEmpty(MaaStringListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaSize MaaStringListBufferSize(MaaStringListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaStringBufferHandle MaaStringListBufferAt(MaaStringListBufferHandle handle, MaaSize index);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaStringListBufferAppend(MaaStringListBufferHandle handle, MaaStringBufferHandle value);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaStringListBufferRemove(MaaStringListBufferHandle handle, MaaSize index);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaStringListBufferClear(MaaStringListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaImageBufferHandle MaaImageBufferCreate();

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaImageBufferDestroy(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaImageBufferIsEmpty(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaImageBufferClear(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaImageRawData MaaImageBufferGetRawData(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaImageBufferWidth(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaImageBufferHeight(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaImageBufferChannels(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaImageBufferType(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaImageBufferSetRawData(MaaImageBufferHandle handle, MaaImageRawData data, int width, int height, int type);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaImageEncodedData MaaImageBufferGetEncoded(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaSize MaaImageBufferGetEncodedSize(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaImageBufferSetEncoded(MaaImageBufferHandle handle, MaaImageEncodedData data, MaaSize size);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaImageListBufferHandle MaaImageListBufferCreate();

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaImageListBufferDestroy(MaaImageListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaImageListBufferIsEmpty(MaaImageListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaSize MaaImageListBufferSize(MaaImageListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaImageBufferHandle MaaImageListBufferAt(MaaImageListBufferHandle handle, MaaSize index);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaImageListBufferAppend(MaaImageListBufferHandle handle, MaaImageBufferHandle value);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaImageListBufferRemove(MaaImageListBufferHandle handle, MaaSize index);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaImageListBufferClear(MaaImageListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaRectHandle MaaRectCreate();

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaRectDestroy(MaaRectHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaRectGetX(MaaRectHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaRectGetY(MaaRectHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaRectGetW(MaaRectHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaRectGetH(MaaRectHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaRectSet(MaaRectHandle handle, int x, int y, int w, int h);
}
