//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

global using MaaImageRawData = nint;
global using MaaImageEncodedData = nint;

using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace MaaFramework.Binding.Interop.Native;

public static partial class MaaBuffer
{
    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaStringBufferHandle MaaStringBufferCreate();

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaStringBufferDestroy(MaaStringBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaStringBufferIsEmpty(MaaStringBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaStringBufferClear(MaaStringBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalUsing(typeof(MaaMarshaller))]
    public static partial string MaaStringBufferGet(MaaStringBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaSize MaaStringBufferSize(MaaStringBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaStringBufferSet(MaaStringBufferHandle handle, string str);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaStringBufferSetEx(MaaStringBufferHandle handle, byte[] str, MaaSize size);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaStringListBufferHandle MaaStringListBufferCreate();

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaStringListBufferDestroy(MaaStringListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaStringListBufferIsEmpty(MaaStringListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaSize MaaStringListBufferSize(MaaStringListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaStringBufferHandle MaaStringListBufferAt(MaaStringListBufferHandle handle, MaaSize index);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaStringListBufferAppend(MaaStringListBufferHandle handle, MaaStringBufferHandle value);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaStringListBufferRemove(MaaStringListBufferHandle handle, MaaSize index);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaStringListBufferClear(MaaStringListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaImageBufferHandle MaaImageBufferCreate();

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaImageBufferDestroy(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaImageBufferIsEmpty(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaImageBufferClear(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaImageRawData MaaImageBufferGetRawData(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaImageBufferWidth(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaImageBufferHeight(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaImageBufferChannels(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaImageBufferType(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaImageBufferSetRawData(MaaImageBufferHandle handle, MaaImageRawData data, int width, int height, int type);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaImageEncodedData MaaImageBufferGetEncoded(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaSize MaaImageBufferGetEncodedSize(MaaImageBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaImageBufferSetEncoded(MaaImageBufferHandle handle, MaaImageEncodedData data, MaaSize size);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaImageListBufferHandle MaaImageListBufferCreate();

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaImageListBufferDestroy(MaaImageListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaImageListBufferIsEmpty(MaaImageListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaSize MaaImageListBufferSize(MaaImageListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaImageBufferHandle MaaImageListBufferAt(MaaImageListBufferHandle handle, MaaSize index);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaImageListBufferAppend(MaaImageListBufferHandle handle, MaaImageBufferHandle value);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaImageListBufferRemove(MaaImageListBufferHandle handle, MaaSize index);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaImageListBufferClear(MaaImageListBufferHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaRectHandle MaaRectCreate();

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaRectDestroy(MaaRectHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaRectGetX(MaaRectHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaRectGetY(MaaRectHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaRectGetW(MaaRectHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial int MaaRectGetH(MaaRectHandle handle);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaRectSet(MaaRectHandle handle, int x, int y, int w, int h);
}
