//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace MaaFramework.Binding.Interop.Native;

public static partial class MaaContext
{
    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaTaskId MaaContextRunTask(MaaContextHandle context, string entry, string pipelineOverride);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaRecoId MaaContextRunRecognition(MaaContextHandle context, string entry, string pipelineOverride, MaaImageBufferHandle image);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaActId MaaContextRunAction(MaaContextHandle context, string entry, string pipelineOverride, MaaRectHandle box, string recoDetail);

    /// <summary>
    ///     Run recognition directly with type and parameters, without requiring a pipeline entry.
    /// </summary>
    /// <param name="context">The context handle.</param>
    /// <param name="recoType">Recognition type string (e.g., "OCR", "TemplateMatch").</param>
    /// <param name="recoParam">Recognition parameters json.</param>
    /// <param name="image">Image to recognize.</param>
    /// <returns>The recognition id.</returns>
    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaRecoId MaaContextRunRecognitionDirect(MaaContextHandle context, string recoType, string recoParam, MaaImageBufferHandle image);

    /// <summary>
    ///     Run action directly with type and parameters, without requiring a pipeline entry.
    /// </summary>
    /// <param name="context">The context handle.</param>
    /// <param name="actionType">Action type string (e.g., "Click", "Swipe").</param>
    /// <param name="actionParam">Action parameters json.</param>
    /// <param name="box">Previous recognition position.</param>
    /// <param name="recoDetail">Previous recognition details.</param>
    /// <returns>The action id.</returns>
    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaActId MaaContextRunActionDirect(MaaContextHandle context, string actionType, string actionParam, MaaRectHandle box, string recoDetail);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaContextOverridePipeline(MaaContextHandle context, string pipelineOverride);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaContextOverrideNext(MaaContextHandle context, string nodeName, MaaStringListBufferHandle nextList);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaContextOverrideImage(MaaContextHandle context, string imageName, MaaImageBufferHandle image);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaContextGetNodeData(MaaContextHandle context, string nodeName, MaaStringBufferHandle buffer);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaTaskId MaaContextGetTaskId(MaaContextHandle context);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaTaskerHandle MaaContextGetTasker(MaaContextHandle context);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaContextHandle MaaContextClone(MaaContextHandle context);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaContextSetAnchor(MaaContextHandle context, string anchorName, string nodeName);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaContextGetAnchor(MaaContextHandle context, string anchorName, MaaStringBufferHandle buffer);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaContextGetHitCount(MaaContextHandle context, string nodeName, out MaaSize count);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaContextClearHitCount(MaaContextHandle context, string nodeName);
}
