//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace MaaFramework.Binding.Interop.Native;

public static partial class MaaResource
{
    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaResourceHandle MaaResourceCreate(MaaNotificationCallback notify, nint notifyTransArg);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaResourceDestroy(MaaResourceHandle res);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaResourceRegisterCustomRecognition(MaaResourceHandle res, string name, MaaCustomRecognitionCallback recognition, nint transArg);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaResourceUnregisterCustomRecognition(MaaResourceHandle res, string name);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaResourceClearCustomRecognition(MaaResourceHandle res);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaResourceRegisterCustomAction(MaaResourceHandle res, string name, MaaCustomActionCallback action, nint transArg);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaResourceUnregisterCustomAction(MaaResourceHandle res, string name);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaResourceClearCustomAction(MaaResourceHandle res);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaResId MaaResourcePostPath(MaaResourceHandle res, string path);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaResourceClear(MaaResourceHandle res);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaStatus MaaResourceStatus(MaaResourceHandle res, MaaResId id);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaStatus MaaResourceWait(MaaResourceHandle res, MaaResId id);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaResourceLoaded(MaaResourceHandle res);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaResourceSetOption(MaaResourceHandle res, MaaResOption key, byte[] value, MaaOptionValueSize valSize);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaResourceGetHash(MaaResourceHandle res, MaaStringBufferHandle buffer);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaResourceGetTaskList(MaaResourceHandle res, MaaStringListBufferHandle buffer);
}
