//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

using System.Runtime.InteropServices;

namespace MaaFramework.Binding.Interop.Native;

public static partial class MaaToolkit
{
    [LibraryImport("MaaToolkit", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaToolkitInitOptionConfig(string userPath, string defaultJson);

    [Obsolete("Use MaaToolkitInitOptionConfig instead.")]
    [LibraryImport("MaaToolkit", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaToolkitInit();

    [Obsolete("Don't use it.")]
    [LibraryImport("MaaToolkit", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaToolkitUninit();
}
