//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

global using MaaActionApiTuple = (
    System.Runtime.InteropServices.GCHandle Handle,
    MaaFramework.Binding.Custom.IMaaCustomAction Managed,
    MaaFramework.Binding.Interop.Native.IMaaCustomActionExtension.RunDelegate RunMethod,
    MaaFramework.Binding.Interop.Native.IMaaCustomActionExtension.AbortDelegate AbortMethod
);

using MaaFramework.Binding.Buffers;
using MaaFramework.Binding.Custom;
using System.Runtime.InteropServices;

namespace MaaFramework.Binding.Interop.Native;

/// <summary>
///     The custom action API.
/// </summary>
/// <remarks>
///     To create a custom action, you need to implement this API.
///     You do not have to implement all the functions in this API. Instead, just implement the functions you need. Do note that if an unimplemented function is called, the framework will likely crash.
/// </remarks>
[StructLayout(LayoutKind.Sequential)]
public class MaaCustomActionApi
{
    public nint RunFunctionPointer;
    public nint AbortFunctionPointer;
}

/// <summary>
///     A static class providing extension methods for the converter of <see cref="IMaaCustomAction"/>.
/// </summary>
public static class IMaaCustomActionExtension
{
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate MaaBool RunDelegate(MaaSyncContextHandle syncContext, [MarshalAs(UnmanagedType.LPUTF8Str)] string taskName, [MarshalAs(UnmanagedType.LPUTF8Str)] string customActionParam, MaaRectHandle curBox, [MarshalAs(UnmanagedType.LPUTF8Str)] string curRecDetail, MaaTransparentArg actionArg);

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void AbortDelegate(MaaTransparentArg actionArg);
    public static MaaCustomActionHandle Convert(this IMaaCustomAction task, out MaaActionApiTuple tuple)
    {
        MaaBool RunLocalMethod(MaaSyncContextHandle syncContext, string taskName, string customActionParam, MaaRectHandle curBox, string curRecDetail, MaaTransparentArg actionArg) => task.Run(new Binding.MaaSyncContext(syncContext), taskName, customActionParam, new Buffers.MaaRectBuffer(curBox), curRecDetail).ToMaaBool();

        void AbortLocalMethod(MaaTransparentArg actionArg) => task.Abort();

        RunDelegate RunMethod = RunLocalMethod;
        AbortDelegate AbortMethod = AbortLocalMethod;

        var handle = GCHandle.Alloc(new MaaCustomActionApi()
        {
            RunFunctionPointer = Marshal.GetFunctionPointerForDelegate<RunDelegate>(RunMethod),
            AbortFunctionPointer = Marshal.GetFunctionPointerForDelegate<AbortDelegate>(AbortMethod),
        }, GCHandleType.Pinned);

        tuple = (
            handle,
            task,
            RunMethod,
            AbortMethod
        );
        return handle.AddrOfPinnedObject();
    }
}
