//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

using System.Runtime.InteropServices;

namespace MaaFramework.Binding.Interop.Native;

public static partial class MaaSyncContext
{
    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSyncContextRunTask(MaaSyncContextHandle syncContext, string taskName, string param);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSyncContextRunRecognition(MaaSyncContextHandle syncContext, MaaImageBufferHandle image, string taskName, string taskParam, MaaRectHandle outBox, MaaStringBufferHandle outDetail);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSyncContextRunAction(MaaSyncContextHandle syncContext, string taskName, string taskParam, MaaRectHandle curBox, string curRecDetail);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSyncContextClick(MaaSyncContextHandle syncContext, int x, int y);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSyncContextSwipe(MaaSyncContextHandle syncContext, int x1, int y1, int x2, int y2, int duration);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSyncContextPressKey(MaaSyncContextHandle syncContext, int keycode);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSyncContextInputText(MaaSyncContextHandle syncContext, string text);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSyncContextTouchDown(MaaSyncContextHandle syncContext, int contact, int x, int y, int pressure);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSyncContextTouchMove(MaaSyncContextHandle syncContext, int contact, int x, int y, int pressure);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSyncContextTouchUp(MaaSyncContextHandle syncContext, int contact);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSyncContextScreencap(MaaSyncContextHandle syncContext, MaaImageBufferHandle outImage);

    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaSyncContextCachedImage(MaaSyncContextHandle syncContext, MaaImageBufferHandle outImage);
}
