//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

namespace MaaFramework.Binding;

/// <summary>
///     ADB controller type.
/// </summary>
/// <remarks>
///     The ADB controller type consists of three parts: touch, key, and screencap. The touch part is used to control the touch events on the device. The key part is used to control the key events on the device. The screencap part is used to capture the screen of the device. The final value is the combination of the three parts as follows:
///     touch_type | key_type | screencap_type
/// </remarks>
[Flags]
public enum AdbControllerTypes
{
    TouchMask = 0xFF,
    KeyMask = 0xFF00,
    ScreencapMask = 0xFF0000,
    Invalid = 0,
    TouchAdb = 1,
    TouchMiniTouch = 2,
    TouchMaaTouch = 3,
    TouchEmulatorExtras = 4,
    TouchAutoDetect = TouchMask - 1,
    KeyAdb = 1 << 8,
    KeyMaaTouch = 2 << 8,
    KeyEmulatorExtras = 3 << 8,
    KeyAutoDetect = KeyMask - (1 << 8),
    InputPresetAdb = TouchAdb | KeyAdb,
    InputPresetMiniTouch = TouchMiniTouch | KeyAdb,
    InputPresetMaaTouch = TouchMaaTouch | KeyMaaTouch,
    InputPresetAutoDetect = TouchAutoDetect | KeyAutoDetect,
    InputPresetEmulatorExtras = TouchEmulatorExtras | KeyEmulatorExtras,
    [Obsolete]
    ScreencapFastestWayCompatible = 1 << 16,
    ScreencapRawByNetcat = 2 << 16,
    ScreencapRawWithGzip = 3 << 16,
    ScreencapEncode = 4 << 16,
    ScreencapEncodeToFile = 5 << 16,
    ScreencapMinicapDirect = 6 << 16,
    ScreencapMinicapStream = 7 << 16,
    ScreencapEmulatorExtras = 8 << 16,
    ScreencapFastestLosslessWay = ScreencapMask - (2 << 16),
    ScreencapFastestWay = ScreencapMask - (1 << 16),
}

