//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

namespace MaaFramework.Binding;

/// <summary>
///     Win32 controller type.
/// </summary>
/// <remarks>
///     See AdbControllerTypeEnum to know how the value is composed.
/// </remarks>
[Flags]
public enum Win32ControllerTypes
{
    TouchMask = 0xFF,
    KeyMask = 0xFF00,
    ScreencapMask = 0xFF0000,
    Invalid = 0,
    TouchSendMessage = 1,
    TouchSeize = 2,
    KeySendMessage = 1 << 8,
    KeySeize = 2 << 8,
    ScreencapGDI = 1 << 16,
    ScreencapDXGIDesktopDup = 2 << 16,
    ScreencapDXGIFramePool = 4 << 16,
}

