//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

namespace MaaFramework.Binding;

/// <summary>
///     Option keys for controller instance options. See MaaControllerSetOption().
/// </summary>
public enum ControllerOption
{
    Invalid = 0,
    /// <summary>
    ///     Only one of long and short side can be set, and the other is automatically scaled according to the aspect ratio.
    /// </summary>
    /// <remarks>
    ///     value: int, eg: 1920; val_size: sizeof(int)
    /// </remarks>
    ScreenshotTargetLongSide = 1,
    /// <summary>
    ///     Only one of long and short side can be set, and the other is automatically scaled according to the aspect ratio.
    /// </summary>
    /// <remarks>
    ///     value: int, eg: 1080; val_size: sizeof(int)
    /// </remarks>
    ScreenshotTargetShortSide = 2,
    /// <summary>
    ///     For StartApp
    /// </summary>
    /// <remarks>
    ///     value: string, eg: "com.hypergryph.arknights/com.u8.sdk.U8UnityContext"; val_size: string
    ///     length
    /// </remarks>
    DefaultAppPackageEntry = 3,
    /// <summary>
    ///     For StopApp
    /// </summary>
    /// <remarks>
    ///     value: string, eg: "com.hypergryph.arknights"; val_size: string length
    /// </remarks>
    DefaultAppPackage = 4,
    /// <summary>
    ///     Dump all screenshots and actions
    /// </summary>
    /// <remarks>
    ///     Recording will evaluate to true if any of this or
    ///     MaaGlobalOptionEnum::MaaGlobalOption_Recording is true.
    ///     value: bool, eg: true; val_size: sizeof(bool)
    /// </remarks>
    Recording = 5,
}

