//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

namespace MaaFramework.Binding;

public enum GlobalOption
{
    Invalid = 0,
    /// <summary>
    ///     Log dir
    /// </summary>
    /// <remarks>
    ///     value: string, eg: "C:\\Users\\Administrator\\Desktop\\log"; val_size: string length
    /// </remarks>
    LogDir = 1,
    /// <summary>
    ///     Whether to save draw
    /// </summary>
    /// <remarks>
    ///     value: bool, eg: true; val_size: sizeof(bool)
    /// </remarks>
    SaveDraw = 2,
    /// <summary>
    ///     Dump all screenshots and actions
    /// </summary>
    /// <remarks>
    ///     Recording will evaluate to true if any of this or MaaCtrlOptionEnum::MaaCtrlOption_Recording
    ///     is true. value: bool, eg: true; val_size: sizeof(bool)
    /// </remarks>
    Recording = 3,
    /// <summary>
    ///     The level of log output to stdout
    /// </summary>
    /// <remarks>
    ///     value: MaaLoggingLevel, val_size: sizeof(MaaLoggingLevel)
    ///     default value is MaaLoggingLevel_Error
    /// </remarks>
    StdoutLevel = 4,
    /// <summary>
    ///     Whether to show hit draw
    /// </summary>
    /// <remarks>
    ///     value: bool, eg: true; val_size: sizeof(bool)
    /// </remarks>
    ShowHitDraw = 5,
    /// <summary>
    ///     Whether to callback debug message
    /// </summary>
    /// <remarks>
    ///     value: bool, eg: true; val_size: sizeof(bool)
    /// </remarks>
    DebugMessage = 6,
}

