//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

﻿namespace MaaFramework.Binding.Messages;

//MaaApiDocument Version: (main) v2.0.0-beta.1
/// <summary>
///  A callback consists of a message and a payload.
///  The message is a string that indicates the type of the message.
///  The payload is a JSON object that contains the details of the message.
/// </summary>
public static class MaaMsg
{
    public static class Resource
    {
        /// <summary>
        ///     The message for the resource loading.
        /// </summary>
        /// <remarks>
        ///     <para>payload: { id: number, path: string }</para>
        /// </remarks>
        public const string StartLoading = "Resource.StartLoading";

        /// <summary>
        ///     The message for the resource loading.
        /// </summary>
        /// <remarks>
        ///     <para>payload: { id: number, path: string }</para>
        /// </remarks>
        public const string LoadingCompleted = "Resource.LoadingCompleted";

        /// <summary>
        ///     The message for the resource loading.
        /// </summary>
        /// <remarks>
        ///     <para>payload: { id: number, path: string }</para>
        /// </remarks>
        public const string LoadingFailed = "Resource.LoadingFailed";

    }
    public static class Controller
    {
        public static class Action
        {
            /// <summary>
            ///     Message for the controller actions.
            /// </summary>
            /// <remarks>
            ///     <para>payload: { id: number }</para>
            /// </remarks>
            public const string Started = "Controller.Action.Started";

            /// <summary>
            ///     Message for the controller actions.
            /// </summary>
            /// <remarks>
            ///     <para>payload: { id: number }</para>
            /// </remarks>
            public const string Completed = "Controller.Action.Completed";

            /// <summary>
            ///     Message for the controller actions.
            /// </summary>
            /// <remarks>
            ///     <para>payload: { id: number }</para>
            /// </remarks>
            public const string Failed = "Controller.Action.Failed";

        }
        /// <summary>
        ///     The message for the UUID got.
        /// </summary>
        /// <remarks>
        ///     <para>payload: { uuid: string }</para>
        /// </remarks>
        public const string UUIDGot = "Controller.UUIDGot";

        public const string UUIDGetFailed = "Controller.UUIDGetFailed";

        /// <remarks>
        ///     <para>payload: { }</para>
        /// </remarks>
        public const string ScreencapInited = "Controller.ScreencapInited";

        public const string ScreencapInitFailed = "Controller.ScreencapInitFailed";

        public const string InputInited = "Controller.TouchinputInited";

        public const string InputInitFailed = "Controller.TouchinputInitFailed";

        /// <summary>
        ///     Message for the controller connected.
        /// </summary>
        /// <remarks>
        ///     <para>payload: { uuid: string }</para>
        /// </remarks>
        public const string ConnectSuccess = "Controller.ConnectSuccess";

        /// <summary>
        ///     Message for the controller connect failed.
        /// </summary>
        /// <remarks>
        ///     <para>payload: { why: string }</para>
        /// </remarks>
        public const string ConnectFailed = "Controller.ConnectFailed";

    }
    public static class Tasker
    {
        public static class Task
        {
            /// <summary>
            ///     Message for the tasks.
            /// </summary>
            /// <remarks>
            ///     <para>payload: { id: number, entry: string, name: string, uuid: string, hash: string }</para>
            /// </remarks>
            public const string Started = "Tasker.Task.Started";

            /// <summary>
            ///     Message for the tasks.
            /// </summary>
            /// <remarks>
            ///     <para>payload: { id: number, entry: string, name: string, uuid: string, hash: string }</para>
            /// </remarks>
            public const string Completed = "Tasker.Task.Completed";

            /// <summary>
            ///     Message for the tasks.
            /// </summary>
            /// <remarks>
            ///     <para>payload: { id: number, entry: string, name: string, uuid: string, hash: string }</para>
            /// </remarks>
            public const string Failed = "Tasker.Task.Failed";

        }
    }
    public static class Task
    {
        public static class Debug
        {
            /// <summary>
            ///     Message for the recognitions.
            /// </summary>
            /// <remarks>
            ///     <para>payload: { task_id: number, entry: string, uuid: string, hash: string, current: string, recognition: { reco_id: number, name: string, box: [number, number, number, number], // If not recognized, it is null detail: any, } }</para>
            /// </remarks>
            public const string RecognitionResult = "Task.Debug.RecognitionResult";

            /// <summary>
            ///     Message for the recognitions.
            /// </summary>
            /// <remarks>
            ///     <para>payload: { task_id: number, entry: string, uuid: string, hash: string, current: string, recognition: { reco_id: number, name: string, box: [number, number, number, number], // If not recognized, it is null detail: any, } }</para>
            /// </remarks>
            public const string Hit = "Task.Debug.Hit";

            /// <summary>
            ///     Message for the task focus.
            /// </summary>
            /// <remarks>
            ///     <para>payload: { task_id: number, entry: string, uuid: string, hash: string, current: string, node: { node_id: number, name: string, reco_id: number, times: number, completed: boolean, } }</para>
            /// </remarks>
            public const string ReadyToRun = "Task.Debug.ReadyToRun";

            /// <summary>
            ///     Message for the task focus.
            /// </summary>
            /// <remarks>
            ///     <para>payload: { task_id: number, entry: string, uuid: string, hash: string, current: string, node: { node_id: number, name: string, reco_id: number, times: number, completed: boolean, } }</para>
            /// </remarks>
            public const string Completed = "Task.Debug.Completed";

            /// <summary>
            ///     Message for the task list.
            /// </summary>
            /// <remarks>
            ///     <para>payload: { task_id: number, entry: string, uuid: string, hash: string, current: string, list: [string], }</para>
            /// </remarks>
            public const string ListToRecognize = "Task.Debug.ListToRecognize";

            /// <summary>
            ///     Message for the task list.
            /// </summary>
            /// <remarks>
            ///     <para>payload: { task_id: number, entry: string, uuid: string, hash: string, current: string, list: [string], }</para>
            /// </remarks>
            public const string MissAll = "Task.Debug.MissAll";

        }
        public static class Focus
        {
            /// <summary>
            ///     Message for the task focus.
            /// </summary>
            /// <remarks>
            ///     <para>payload: { task_id: number, entry: string, uuid: string, hash: string, current: string, node: { node_id: number, name: string, reco_id: number, times: number, completed: boolean, } }</para>
            /// </remarks>
            public const string ReadyToRun = "Task.Focus.ReadyToRun";

            /// <summary>
            ///     Message for the task focus.
            /// </summary>
            /// <remarks>
            ///     <para>payload: { task_id: number, entry: string, uuid: string, hash: string, current: string, node: { node_id: number, name: string, reco_id: number, times: number, completed: boolean, } }</para>
            /// </remarks>
            public const string Completed = "Task.Focus.Completed";

        }
    }
    public const string Invalid = "Invalid";

}