//------------------------------------------------------------------------------
// <auto-generated>
//     This code was manually generated.
//
//     Deleting it will report errors: CA1401, CA1711, S4200.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

using System.Runtime.InteropServices;
namespace MaaFramework.Binding.Interop.Native;

public static partial class MaaBuffer
{
    [LibraryImport("MaaFramework", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaBool MaaStringBufferSetEx(MaaStringBufferHandle handle, nint str, MaaSize size);
}
