//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1573 // 参数在 XML 注释中没有匹配的 param 标记
#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace MaaFramework.Binding.Interop.Native;

public static partial class MaaAgentServer
{
    [LibraryImport("MaaAgentServer", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaAgentServerRegisterCustomRecognition(string name, MaaCustomRecognitionCallback recognition, nint transArg);

    [LibraryImport("MaaAgentServer", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaAgentServerRegisterCustomAction(string name, MaaCustomActionCallback action, nint transArg);

    [LibraryImport("MaaAgentServer", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaSinkId MaaAgentServerAddResourceSink(MaaEventCallback sink, nint transArg);

    [LibraryImport("MaaAgentServer", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaSinkId MaaAgentServerAddControllerSink(MaaEventCallback sink, nint transArg);

    [LibraryImport("MaaAgentServer", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaSinkId MaaAgentServerAddTaskerSink(MaaEventCallback sink, nint transArg);

    [LibraryImport("MaaAgentServer", StringMarshalling = StringMarshalling.Utf8)]
    public static partial MaaSinkId MaaAgentServerAddContextSink(MaaEventCallback sink, nint transArg);

    [LibraryImport("MaaAgentServer", StringMarshalling = StringMarshalling.Utf8)]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool MaaAgentServerStartUp(string identifier);

    [LibraryImport("MaaAgentServer", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaAgentServerShutDown();

    [LibraryImport("MaaAgentServer", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaAgentServerJoin();

    [LibraryImport("MaaAgentServer", StringMarshalling = StringMarshalling.Utf8)]
    public static partial void MaaAgentServerDetach();
}
