name: cd

on:
  workflow_dispatch:
    inputs:
      Publish:
        description: 'Publish option'
        required: true
        default: 'None'
        type: choice
        options:
          - None
          - NuGet
          - NuGetTest
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/cd.yml"
    tags:
      - "v*"

jobs:
  release:
    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages # NuGet CLI environment variables
      NUGET_PACKAGE_SOURCE: https://api.nuget.org/v3/index.json # need ${{ secrets.NUGET_TOKEN }} or ${{ secrets.NUGETALL_TOKEN }} (Expires in a day)
      NUGETTEST_PACKAGE_SOURCE: https://apiint.nugettest.org/v3/index.json # need ${{ secrets.NUGETTEST_TOKEN }} (Expires in a day)

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            7.0.x
            8.0.x
          cache: true
          cache-dependency-path: '**/packages.lock.json'
      - run: dotnet restore --locked-mode

      - id: meta
        shell: bash
        run: |
          is_release=${{ startsWith(github.ref, 'refs/tags/v') }}
          tag=$(git describe --tags --match "v*" ${{ github.ref }} || true)
          if ! $($is_release) ; then
            prefix=${tag%-*-*}
            suffix=${tag#$prefix-}
            tag="$prefix-ci.$suffix"
          fi

          echo tag=$tag | tee -a $GITHUB_OUTPUT
          echo version=${tag#v} | tee -a $GITHUB_OUTPUT
          echo is_release=$is_release | tee -a $GITHUB_OUTPUT

      - name: Build
        run: |
          dotnet build --configuration Release --no-restore -p:Version=${{ steps.meta.outputs.version }} -p:RepositoryBranch=$(git rev-parse --abbrev-ref HEAD) -p:RepositoryCommit=$(git rev-parse HEAD)
          mv ./src/**/bin/Release/*nupkg ./

      - name: Publish the package to nugettest.org
        if: ${{ steps.meta.outputs.is_release == 'false' || github.event.inputs.Publish == 'NuGetTest' }}
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGETTEST_TOKEN }} --source ${{ env.NUGETTEST_PACKAGE_SOURCE }}

      - name: Publish the package to nuget.org
        if: ${{ steps.meta.outputs.is_release == 'true' || github.event.inputs.Publish == 'NuGet' }}
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source ${{ env.NUGET_PACKAGE_SOURCE }}

      - uses: softprops/action-gh-release@v2
        if: ${{ steps.meta.outputs.is_release == 'true' }}
        with:
          body_path: CHANGELOG.md
          tag_name: ${{ steps.meta.outputs.tag }}
