name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/ci.yml"
      - "tools/Builder/Build.csx"
      - "tools/Linters/NamespaceLinter.csx"
      - "src/**"
      - "*.sln"
      - "*.props"

  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/ci.yml"
      - "tools/Builder/Build.csx"
      - "tools/Linters/NamespaceLinter.csx"
      - "src/**"
      - "*.sln"
      - "*.props"

jobs:
  build:
    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages # NuGet CLI environment variables
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            7.0.x
            8.0.x
          cache: true
          cache-dependency-path: '**/packages.lock.json'
      - run: dotnet restore --locked-mode
      - run: dotnet tool install -g dotnet-script

      - id: build
        env:
          GH_TOKEN: ${{ github.token }}
        run: dotnet script ./tools/Builder/Build.csx

      - uses: actions/upload-artifact@v4
        with:
          name: nupkgs
          path: ./nupkgs
          retention-days: 1

      - if: github.ref == 'refs/heads/${{ steps.build.outputs.default_branch }}' && github.repository_owner_id == '161146573'
        uses: moomiji/host-nuget-on-github@v1
        with:
          base-uri: https://maaxyz.github.io/pkg/nuget/
          package-paths: ./nupkgs
          feed-path: nuget
          force: true
          repository: MaaXYZ/pkg
          branch: main
          token: ${{ secrets.PKG_TOKEN }}

  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
      - run: dotnet tool install -g dotnet-script
      - run: cd tools/Linters ; dotnet script ./NamespaceLinter.csx
