name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "*.sln"
      - "*.props"

  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "*.sln"
      - "*.props"

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest ] # [windows-latest, ubuntu-latest, macos-latest]
        arch: [ x86_64 ] # [aarch64, x86_64]
        dotnet: [ '7.0', '8.0' ]
      fail-fast: false
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages # NuGet CLI environment variables

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
          cache: true
          cache-dependency-path: '**/packages.lock.json'
      - run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --configuration Release --no-restore --framework net${{ matrix.dotnet }}

  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
      - run: dotnet tool install -g dotnet-script ; cd tools/Linters ; dotnet script ./NamespaceLinter.cs
