name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "*.sln"
      - "*.props"

  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "*.sln"
      - "*.props"

jobs:
  build:
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages # NuGet CLI environment variables

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            7.0.x
            8.0.x
          cache: true
          cache-dependency-path: '**/packages.lock.json'
      - run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - uses: actions/upload-artifact@v3
        with:
          name: nupkgs
          path: | 
            src/**/*.nupkg
            src/**/*.snupkg
          retention-days: 30

  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
      - run: dotnet tool install -g dotnet-script ; cd tools/Linters ; dotnet script ./NamespaceLinter.cs
